%% Generate CARTO and EnSiteX demonstration outputs

openepRoot = fileparts(fileparts(mfilename('fullpath')));
projectRoot = fileparts(openepRoot);
outputRoot = fullfile(projectRoot, 'demo_outputs');

addpath(openepRoot);

if ~isfolder(outputRoot)
    mkdir(outputRoot);
end

cartoInput = fullfile( ...
    projectRoot, ...
    'full_cases', ...
    'Carto', ...
    'ReCETT-AF', ...
    'Study1-Williams-Edinburgh', ...
    'Export_PAF-02_28_2023-14-19-48.zip');

cartoResult = convert_mapping_case( ...
    cartoInput, ...
    fullfile(outputRoot, 'carto_study1_2LA.mat'), ...
    'system', 'carto', ...
    'maptoread', '2-LA', ...
    'refchannel', 'CS1-CS2', ...
    'ecgchannel', 'V1');

ensiteInput = fullfile( ...
    projectRoot, ...
    'full_cases', ...
    'EnsiteX', ...
    'Brussels', ...
    'Study3-Gharaviri-Brussels');

ensiteResult = convert_mapping_case( ...
    ensiteInput, ...
    fullfile(outputRoot, 'ensitex_study3_all.mat'), ...
    'system', 'ensitex', ...
    'maptoread', 'VoXel SR 1 ENDO', ...
    'modes', {'bi', 'uni', 'omni'});

disp(cartoResult);
disp(ensiteResult);

assert(cartoResult.success, cartoResult.error.message);
assert(ensiteResult.success, ensiteResult.error.message);

fprintf('\nDemo outputs written to:\n%s\n', outputRoot);
